@api = http://localhost:3000/tasks

GET {{api}}

### Create Task

POST {{api}}
Content-Type: application/json

{
  "name": "Buy Milk",
  "Content": "Go to the store and buy milk",
  "completed": false
}